### ISSUE TITLE
I want reopen #465

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [kubb-project/kubb#469]
### What platform is your computer?

MacOS

### How did you attempt to install or upgrade?

`PluginError: Cannot read properties of undefined (reading 'isBatchingLegacy')` Error occurs.

refer to https://github.com/kubb-project/kubb/issues/465#issuecomment-1755415232

### What do you see instead?

.

**Comment by stijnvanhulle** [comment]
The issue lies in the fact that `react-reconciler` is using `react` 18 but also has the peerDependencies flag set.

A custom React-dom(@kubb/react-template) is currently used(**experimental**) to create generated code based on React components. This should be internal and should have no impact on users so I decided to include all that is needed in the bundle itself(no React dependency when React is not set in the users `package.json`).

https://github.com/kubb-project/kubb/pull/470

**Comment by essential-randomness** [comment]
Worked for me :)

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
`1.10.3` works well! Thanks :)
